# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "America/Toronto"
    target-branch: "develop"
    assignees:
      - "bobokun"
    # Specify the file to check for dependencies
    # Dependabot will now look at pyproject.toml instead of requirements.txt
    allow:
      - dependency-type: "direct"
    # Specify the file to update
    versioning-strategy: increase-if-necessary
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "America/Toronto"
    assignees:
      - "bobokun"
    target-branch: "develop"
    ignore:
      - dependency-name: "salsify/action-detect-and-tag-new-version"
